crypto: nx - add missing CRYPTO_ACOMP2 select
The nx-compress driver uses crypto_register_scomp() and
crypto_unregister_scomp() (provided by crypto/scompress.c, gated by
CRYPTO_ACOMP2), but CRYPTO_DEV_NX_COMPRESS does not select
CRYPTO_ACOMP2.  This previously worked because CRYPTO_MANAGER2
unconditionally selected CRYPTO_ACOMP2, but commit cdadc1435937
("crypto: cryptomgr - Select algorithm types only when
CRYPTO_SELFTESTS") gated those selects on CRYPTO_SELFTESTS.

In configurations with CRYPTO_DEV_NX_COMPRESS_PSERIES=y or
CRYPTO_DEV_NX_COMPRESS_POWERNV=y and CRYPTO_SELFTESTS=n, the build
now fails with:

  ld: drivers/crypto/nx/nx-common-pseries.o: in function `nx842_probe':
  nx-common-pseries.c:(.text+0x1078): undefined reference to `crypto_register_scomp'
  ld: drivers/crypto/nx/nx-common-pseries.o: in function `nx842_remove':
  nx-common-pseries.c:(.text.unlikely+0x88): undefined reference to `crypto_unregister_scomp'
  ld: drivers/crypto/nx/nx-common-pseries.o: in function `nx842_pseries_exit':
  nx-common-pseries.c:(.exit.text+0x38): undefined reference to `crypto_unregister_scomp'
  ld: drivers/crypto/nx/nx-common-powernv.o: in function `nx_compress_powernv_exit':
  nx-common-powernv.c:(.exit.text+0x34): undefined reference to `crypto_unregister_scomp'
  ld: drivers/crypto/nx/nx-common-powernv.o: in function `nx_compress_powernv_init':
  nx-common-powernv.c:(.init.text+0x97c): undefined reference to `crypto_register_scomp'

Add the missing select to CRYPTO_DEV_NX_COMPRESS, matching the pattern
already used by every other in-tree compression driver (CRYPTO_842,
CRYPTO_DEFLATE, CRYPTO_LZO, CRYPTO_LZ4, CRYPTO_LZ4HC, CRYPTO_ZSTD).

Fixes: cdadc1435937 ("crypto: cryptomgr - Select algorithm types only when CRYPTO_SELFTESTS")
Change-Id: If0c87a00b1f456797e5391bf4744aad01b75c916
Signed-off-by: Alexei Lazar <alazar@nvidia.com>